name: Build Push and Update Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Create temp directory
        run: |
          mkdir -p C:/temp/actions-tallerSpringAngular
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: C:/temp/actions-tallerSpringAngular
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build angular image
        uses: docker/build-push-action@v6
        with:
          context: C:/temp/actions-tallerSpringAngular/angular
          file: C:/temp/actions-tallerSpringAngular/angular/Dockerfile
          push: true
          tags: valeal/training-angular:0.0.1-SNAPSHOT
      - name: Build spring image
        uses: docker/build-push-action@v6
        with:
          context: C:/temp/actions-tallerSpringAngular/trainingspringboot
          file: C:/temp/actions-tallerSpringAngular/trainingspringboot/Dockerfile
          push: true
          tags: valeal/trainingspringboot:0.0.1-SNAPSHOT
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f C:/temp/actions-tallerSpringAngular/springboot-deployment.yaml
          kubectl apply -f C:/temp/actions-tallerSpringAngular/angular-deployment.yaml